document.writeln("<div class=\'ease_header pdlr20\'>");
document.writeln("    <div class=\'container clearfix\'>");
document.writeln("        <a href=\'#\' class=\'fl easy_logo\'></a>");
document.writeln("        <ul class=\'easy_nav fl\'>");
document.writeln("            <li><a class=\'current\' href=\'javascript:;\'><span>创建单元考试</span></a></li>");
document.writeln("            <li><a href=\'javascript:;\'><span>创建年级考试</span></a></li>");
document.writeln("            <li><a href=\'javascript:;\'><span>创建联考</span></a></li>");
document.writeln("            <li><a href=\'javascript:;\'><span>设置</span></a></li>");
document.writeln("        </ul>");
document.writeln("        <dl class=\'easy_info fr\'>");
document.writeln("            <dt>");
document.writeln("                <a class=\'scan_card\' href=\'#\'><i class=\'icon_scan\'></i><span>扫描答题卡</span></a>");
document.writeln("            </dt>");
document.writeln("            <dt>");
document.writeln("            <div class=\'uerbox\'>");
document.writeln("                <p class=\'userinfo\'>");
document.writeln("                    <span class=\'user_img\'><img src=\'images/upload/user.png\' alt=\'\'></span><a class=\'user_name\'>李小明</a><i class=\'icon_drop\'></i>");
document.writeln("                </p>");
document.writeln("                <div class=\'drop_wrap\'>");
document.writeln("                    <ul class=\'user_droplist\'>");
document.writeln("                        <li><a href=\'javascript:;\'><span>我的班级</span></a></li>");
document.writeln("                        <li><a href=\'javascript:;\'><span>退出登录</span></a></li>");
document.writeln("                    </ul>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("            </dt>");
document.writeln("        </dl>");
document.writeln("    </div>");
document.writeln("</div>");